spring:
 application:
    name: giphermanager
 data:
   mongodb:
     uri: ${MONGO_URL}
     database: FavouriteGifDB
server:
 port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka